// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2qv2anNiztd9okXuAn3-MZr0sPYOxECw',
    appId: '1:507432896047:web:17dee877f66a361eb728da',
    messagingSenderId: '507432896047',
    projectId: 'flashchat-f43cc',
    authDomain: 'flashchat-f43cc.firebaseapp.com',
    storageBucket: 'flashchat-f43cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFOE42OtjnBD_lQKPQFfWUvxhax09nUkk',
    appId: '1:507432896047:android:f163b50ba2a74dacb728da',
    messagingSenderId: '507432896047',
    projectId: 'flashchat-f43cc',
    storageBucket: 'flashchat-f43cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn18zAw-ou26m2_DwMX9lT7p0SRck6ZpQ',
    appId: '1:507432896047:ios:b4c2c3da3dfb2f51b728da',
    messagingSenderId: '507432896047',
    projectId: 'flashchat-f43cc',
    storageBucket: 'flashchat-f43cc.appspot.com',
    iosBundleId: 'com.example.ancilmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn18zAw-ou26m2_DwMX9lT7p0SRck6ZpQ',
    appId: '1:507432896047:ios:68093fe2c605230cb728da',
    messagingSenderId: '507432896047',
    projectId: 'flashchat-f43cc',
    storageBucket: 'flashchat-f43cc.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2qv2anNiztd9okXuAn3-MZr0sPYOxECw',
    appId: '1:507432896047:web:dfb017f0e40e745eb728da',
    messagingSenderId: '507432896047',
    projectId: 'flashchat-f43cc',
    authDomain: 'flashchat-f43cc.firebaseapp.com',
    storageBucket: 'flashchat-f43cc.appspot.com',
  );
}
